name: Build and test
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm t
